# Generated by Django 4.2 on 2023-04-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=200, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Títuloo')),
                ('descricao', models.TextField(verbose_name='Descriçãoo')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criaçãoo')),
                ('prazo_para_conclusao', models.DateTimeField(verbose_name='Prazo para conclusão')),
                ('situacao', models.CharField(choices=[('P', 'PENDENTE'), ('C', 'CONCLUÍDA'), ('A', 'ATRASADA'), ('X', 'PRÓXIMA DE EXPIRAR')], default='P', max_length=1)),
            ],
        ),
    ]
