# Generated by Django 4.2 on 2023-04-04 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_pessoa_tarefas_alter_tarefa_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='tarefas',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='tarefas.pessoa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
