# Generated by Django 4.2 on 2023-04-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_remove_pessoa_tarefas_tarefa_pessoa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tarefas',
            field=models.ManyToManyField(blank=True, to='tarefas.tarefa'),
        ),
    ]
