# Generated by Django 4.2 on 2023-04-04 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_remove_tarefa_pessoa_pessoa_tarefas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='tarefas',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='tarefas.pessoa'),
        ),
    ]
